# NUMPY ARRAYS TUTORIAL


In [1]:
# Import Numpy where np is alias
import numpy as np


In [2]:
print(np)


<module 'numpy' from 'c:\\Python3.10\\lib\\site-packages\\numpy\\__init__.py'>


In [3]:
# Check Numpy Version
print("Numpy Version is "+np.__version__)


Numpy Version is 1.24.2


# Creating Array


In [4]:
# Creating Array
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [5]:
# Print Array
print(arr)
# Print the Type of the 1D Array
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Create Numpy Array using Tuple
tupleArr = np.array((10, 20, 30, 40, 50))
print(tupleArr)


[10 20 30 40 50]


# 0-D Array


In [7]:
# Creating 0 Dimensional Array
zeroDArr = np.array(42)
zeroDArr


array(42)

In [8]:
print(zeroDArr)


42


In [9]:
# Array Size
zeroDArr.size


1

In [10]:
# Check Number or Dimensions
zeroDArr.ndim


0

In [11]:
# Array Shape
zeroDArr.shape


()

# 1-D Array


In [12]:
# Creating 1 Dimensional Array
oneDArr = np.array([1, 2, 3, 4, 5])
oneDArr


array([1, 2, 3, 4, 5])

In [13]:
print(oneDArr)


[1 2 3 4 5]


In [14]:
# Array Size
oneDArr.size


5

In [15]:
# Check Number or Dimensions
oneDArr.ndim


1

In [16]:
# Accessing Array Elements
print(oneDArr[0])
print(oneDArr[3])


1
4


In [17]:
# Array Slicing
print(oneDArr[1:5])


[2 3 4 5]


In [18]:
# Negative Indexing
print(oneDArr[-1])


5


In [19]:
# Value Change by Index
oneDArr[3] = 45
print(oneDArr)


[ 1  2  3 45  5]


In [20]:
# Array Shape
oneDArr.shape


(5,)

In [21]:
# Array ArgMax = Return the index of Maximum Value
oneDArr.argmax()


3

In [22]:
# Array ArgMin = Return the index of Minimum Value
oneDArr.argmin()


0

In [23]:
# Array ArgSort = Return the index of Sorted Order by value
oneDArr.argsort()


array([0, 1, 2, 4, 3], dtype=int64)

In [24]:
# Array Min = Return Minimum Value
oneDArr.min()


1

In [25]:
# Array Max = Return Maximum Value
oneDArr.max()


45

In [26]:
# Array Sort = Return Value by Sorted Order
oneDArr.sort()
print(oneDArr)


[ 1  2  3  5 45]


# 2-D Array


In [27]:
# Creating 2 Dimensional Array
twoDArr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
twoDArr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(twoDArr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
# Array Size
twoDArr.size


10

In [30]:
# Check Number or Dimensions
twoDArr.ndim


2

In [31]:
# Accessing Array Elements
print(twoDArr[0, 3])
print(twoDArr[1, 1])


4
7


In [32]:
# Negative Indexing
print(twoDArr[-1, -2])


9


In [33]:
# Array Slicing
print(twoDArr[1, 0:3])
print(twoDArr[0:2, 2])
print(twoDArr[0:2, 1:4])


[6 7 8]
[3 8]
[[2 3 4]
 [7 8 9]]


In [34]:
# Value Change by Index
twoDArr[1, 3] = 55
print(twoDArr)


[[ 1  2  3  4  5]
 [ 6  7  8 55 10]]


In [35]:
# Array Shape
twoDArr.shape


(2, 5)

In [36]:
# Array ArgMax = Return the index of Maximum Value
# For 2-D to N-D array it will convert first 1-D array then find max value then return it index
twoDArr.argmax()


8

In [37]:
# Array ArgMin = Return the index of Minimum Value
# For 2-D to N-D array it will convert first 1-D array then find min value then return it index
twoDArr.argmin()


0

In [38]:
# Array ArgSort = Return the index of Sorted Order by value
twoDArr.argsort()


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 4, 3]], dtype=int64)

In [39]:
# Array Min = Return Minimum Value
twoDArr.min()


1

In [40]:
# Array Max = Return Maximum Value
twoDArr.max()


55

In [41]:
# Array Sort = Return Value by Sorted Order
twoDArr.sort()
print(twoDArr)


[[ 1  2  3  4  5]
 [ 6  7  8 10 55]]


# 3-D Array


In [42]:
# Creating 3 Dimensional Array
threeDArr = np.array([[[6, 7, 8, 1, 2,], [5, 9, 10, 3, 4, ]], [
                     [10, 30, 40, 20,  50], [80, 90, 100, 60, 70]]])
threeDArr


array([[[  6,   7,   8,   1,   2],
        [  5,   9,  10,   3,   4]],

       [[ 10,  30,  40,  20,  50],
        [ 80,  90, 100,  60,  70]]])

In [43]:
print(threeDArr)


[[[  6   7   8   1   2]
  [  5   9  10   3   4]]

 [[ 10  30  40  20  50]
  [ 80  90 100  60  70]]]


In [44]:
# Array Size
threeDArr.size


20

In [45]:
# Check Number or Dimensions
threeDArr.ndim


3

In [46]:
# Accessing Array Elements
print(threeDArr[0, 1, 4])
print(threeDArr[1, 0, 2])


4
40


In [47]:
# Negative Indexing
print(threeDArr[-2, -2, -4])


7


In [48]:
# Array Slicing
print(threeDArr[1, 0:2, 2:4])
print(threeDArr[0:2:1, 1:3])
print(threeDArr[0:2, 0:2, 2:4])


[[ 40  20]
 [100  60]]
[[[  5   9  10   3   4]]

 [[ 80  90 100  60  70]]]
[[[  8   1]
  [ 10   3]]

 [[ 40  20]
  [100  60]]]


In [49]:
# Value Change by Index
threeDArr[1, 0, 4] = 87
print(threeDArr)


[[[  6   7   8   1   2]
  [  5   9  10   3   4]]

 [[ 10  30  40  20  87]
  [ 80  90 100  60  70]]]


In [50]:
# Array Shape
threeDArr.shape


(2, 2, 5)

In [51]:
# Array ArgMax = Return the index of Maximum Value
# For 2-D to N-D array it will convert first 1-D array then find max value then return it index
threeDArr.argmax()


17

In [52]:
# Array ArgMin = Return the index of Minimum Value
# For 2-D to N-D array it will convert first 1-D array then find min value then return it index
threeDArr.argmin()


3

In [53]:
# Array ArgSort = Return the index of Sorted Order by value
threeDArr.argsort()


array([[[3, 4, 0, 1, 2],
        [3, 4, 0, 1, 2]],

       [[0, 3, 1, 2, 4],
        [3, 4, 0, 1, 2]]], dtype=int64)

In [54]:
# Array Min = Return Minimum Value
threeDArr.min()


1

In [55]:
# Array Max = Return Maximum Value
threeDArr.max()


100

In [56]:
# Array Sort = Return Value by Sorted Order
threeDArr.sort()
print(threeDArr)


[[[  1   2   6   7   8]
  [  3   4   5   9  10]]

 [[ 10  20  30  40  87]
  [ 60  70  80  90 100]]]


# Higher Dimensional Arrays


In [57]:
# Creating Higher Dimensional Array
higherDArray = np.array([100, 200, 300, 400], ndmin=5)
higherDArray


array([[[[[100, 200, 300, 400]]]]])

In [58]:
print(higherDArray)


[[[[[100 200 300 400]]]]]


In [59]:
# Array Size
higherDArray.size


4

In [60]:
# Check Number or Dimensions
higherDArray.ndim


5

In [61]:
# Accessing Array Elements
print(higherDArray[0, 0, 0, 0, 0])
print(higherDArray[0, 0, 0, 0, 2])


100
300


In [62]:
# Negative Indexing
print(higherDArray[-1, -1, -1, -1, -3])


200


In [63]:
# Value Change by Index
higherDArray[0, 0, 0, 0, 2] = 780
print(higherDArray)


[[[[[100 200 780 400]]]]]


In [64]:
# Array Shape
higherDArray.shape


(1, 1, 1, 1, 4)

# Numpy Array Data Types


In [65]:
# Array Integer Data Type
arrI = np.array([4, 5, 6, 7, 8])
print(arrI.dtype)


int32


In [66]:
# Array String Data Type
arrS = np.array(['Apple', 'Banana', 'Orange', 'Cucumber'])
print(arrS.dtype)


<U8


In [67]:
# Array Boolean Data Type
arrB = np.array([False, True, False, True])
print(arrB.dtype)


bool


In [68]:
# Array Float Data Type
arrF = np.array([24.58, 75.26, -85.32, -75.102])
print(arrF.dtype)


float64


In [69]:
# Array Complex Data Type
arrC = np.array([3+2j, 8+0j, 4-9j, 0j])
print(arrC.dtype)


complex128


In [70]:
# Array Mixing Values
arrM = np.array([10, 'Shilajit', 5+4j, False, None, 78.45])
print(arrM)
print(arrM.dtype)


[10 'Shilajit' (5+4j) False None 78.45]
object


# Setting Datatype


In [71]:
# Setting Integer32
arrInt32 = np.array([10, 45, 57, 63], np.int32)
print(arrInt32)
print(arrInt32.dtype)


[10 45 57 63]
int32


In [72]:
# Setting String from Integer
arrString = np.array([1, 2, 3, 4, 5], dtype='S')
print(arrString)
print(arrString.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1


In [73]:
# Setting Integer 8 Bytes
arrInteger = np.array([1, 2, 3, 4, 5], dtype='i8')
print(arrInteger)
print(arrInteger.dtype)


[1 2 3 4 5]
int64


In [74]:
# Setting Integer from Float
arrInteger = np.array([1.2, 2.4, 3.4, 4, 5.8], dtype='i')
print(arrInteger)
print(arrInteger.dtype)


[1 2 3 4 5]
int32


In [75]:
# Setting Float from Integer
arrFloat = np.array([1, 2, 3, 4, 5], dtype='f')
print(arrFloat)
print(arrFloat.dtype)


[1. 2. 3. 4. 5.]
float32


In [76]:
# As Type for Integer
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [77]:
# As Type for Boolean
arr = np.array([1, 0, 3, -1])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[ True False  True  True]
bool


# Copy And View


In [78]:
# Copy
fruits = np.array(['Mango', 'Apple', 'Guava', 'Orange'])
newFruits = fruits.copy()

fruits[1] = 'Banana'
# Original Array Change with Banana
print(fruits)
# Copy Array not change with Banana
print(newFruits)


['Mango' 'Banana' 'Guava' 'Orange']
['Mango' 'Apple' 'Guava' 'Orange']


In [79]:
# Copy
fruits = np.array(['Mango', 'Apple', 'Guava', 'Orange'])
newFruits = fruits.copy()

newFruits[1] = 'Banana'
# Original Array not change with Banana
print(fruits)
# Copy Array Change with Banana
print(newFruits)


['Mango' 'Apple' 'Guava' 'Orange']
['Mango' 'Banana' 'Guava' 'Orange']


In [80]:
# View
cars = np.array(["Toyota", "Honda", "Ford", "Chevrolet", "Nissan"])
newCars = cars.view()

cars[3] = 'Audi'
# Original Array Change with Audi
print(cars)
# Copy Array Change with Audi
print(newCars)


['Toyota' 'Honda' 'Ford' 'Audi' 'Nissan']
['Toyota' 'Honda' 'Ford' 'Audi' 'Nissan']


In [81]:
# View
cars = np.array(["Toyota", "Honda", "Ford", "Chevrolet", "Nissan"])
newCars = cars.view()

newCars[3] = 'Audi'
# Original Array Change with Audi
print(cars)
# Copy Array Change with Audi
print(newCars)


['Toyota' 'Honda' 'Ford' 'Audi' 'Nissan']
['Toyota' 'Honda' 'Ford' 'Audi' 'Nissan']


In [82]:
# Base for Check Data
copyVsview = np.array([145, 4, 155, 742, 5])
x = copyVsview.copy()
y = copyVsview.view()

print(x.base)
print(y.base)


None
[145   4 155 742   5]


# Numpy Zeros


In [83]:
# Create an numpy array where all values are zeros and array shape is 2,5 i.e, a 2-D array where each row consits 5 columns
zero = np.zeros((2, 5))
zero


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
print(zero.dtype)
print(zero.ndim)
print(zero.shape)


float64
2
(2, 5)


# Numpy Arange


In [85]:
# Create an numpy array 0 to 14
arn = np.arange(15)
arn


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
# Create an numpy array 0 to 999
arn = np.arange(1000)
arn


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

# Numpy LinearSpace


In [87]:
# Create an numpy array
# First Params => 1 - this is the array first element
# Second Params => 10 - this is the array last element
# Third Params => 4 - it means array consist 4 elements where each elements are equally difference with each other
lSpace = np.linspace(1, 10, 4)
# Its print [ 1.,  4.,  7., 10.]
# So 2nd element - 1st element = 4-1 = 3
# So 3rd element - 2nd element = 7-4 = 3
# So 4th element - 3rd element = 10-7 = 3
# So each elements are linearly spaced or equally difference with each other
lSpace


array([ 1.,  4.,  7., 10.])

In [88]:
lNewSpace = np.linspace(1, 50, 10)
lNewSpace


array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [89]:
lNewSpace = np.linspace(1, 10000000, 10)
lNewSpace


array([1.000000e+00, 1.111112e+06, 2.222223e+06, 3.333334e+06,
       4.444445e+06, 5.555556e+06, 6.666667e+06, 7.777778e+06,
       8.888889e+06, 1.000000e+07])

# Numpy Empty & Empty_Like


In [90]:
# Create an empty array where random values are present
# This array have 4 rows and 6 columns
emp = np.empty((4, 6))
emp


array([[8.29745336e-312, 7.16395186e-322, 0.00000000e+000,
        0.00000000e+000, 2.05833592e-312, 1.16095484e-028],
       [9.34581354e+252, 5.29862103e+180, 2.13418214e+161,
        1.35749225e-153, 1.96088859e+243, 1.05118798e-153],
       [1.05220982e-153, 5.28595560e-085, 4.07177408e+223,
        9.15279752e+242, 9.15674973e+135, 1.07441485e+160],
       [3.65979186e-086, 4.07188713e+223, 6.48224637e+170,
        3.67145870e+228, 1.30887882e-071, 8.70018275e-313]])

In [91]:
emp.dtype


dtype('float64')

In [92]:
empL = np.empty_like(lSpace)
empL


array([ 1.,  4.,  7., 10.])

In [93]:
# Matrix Example
mA = np.empty_like([2, 2], dtype='i')
mA


array([         0, 1097011920], dtype=int32)

In [94]:
mB = mA = ([1, 2, 3], [4, 5, 6])
print(np.empty_like(mB))


[[   94947424         391           0]
 [          0           1 -2113830140]]


# Numpy Identity


In [95]:
# Create a 3 X 3 Identity Matrix
ide = np.identity((3))
ide


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
# Create a 45 X 45 Identity Matrix
ideN = np.identity((45))
print(ideN)
print(ideN.shape)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(45, 45)


# Numpy Reshape


In [97]:
# Create a 1D array with 99 elements
arrOne = np.arange(99)
arrOne


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [98]:
# Reshape with 3 X 33 Matrix
arrOne = arrOne.reshape(3, 33)
arrOne


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [99]:
# Reshape with 3D array
arrOne = arrOne.reshape(3, 3, 11)
arrOne


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]],

       [[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
        [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]],

       [[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
        [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
        [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]]])

In [100]:
# Convert N-D array to 1-D Array using reshape
arrTwo = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
# Before Conversion
print(arrTwo)
# It will convert the 2-D array to 1-D array
arrTwo = arrTwo.reshape(-1)
# After Conversion
print(arrTwo)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Numpy Ravel


In [101]:
# Convert N-D array to 1-D Array
nrt = np.array([
    [78, 527, 16, 86, 31, 48],
    [45, 12, 67, 53, 98, 100],
    [-875, -53, -76, -42, -24, -732],
    [7225, 785, -875, 12, -645, 2000],
])
print(nrt)
# It will convert the 2-D array to 1-D array
nrt = nrt.ravel()
print(nrt)


[[  78  527   16   86   31   48]
 [  45   12   67   53   98  100]
 [-875  -53  -76  -42  -24 -732]
 [7225  785 -875   12 -645 2000]]
[  78  527   16   86   31   48   45   12   67   53   98  100 -875  -53
  -76  -42  -24 -732 7225  785 -875   12 -645 2000]


# Numpy Array Axis


In [102]:
x = [
    [1, 2, 3,],
    [4, 5, 6],
    [7, 0, 1]
]
arrAxis = np.array(x)
arrAxis


array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [103]:
# Sum of All Element in the Array
arrAxis.sum()


29

In [104]:
# Sum of Y axis value
arrAxis.sum(axis=0)


array([12,  7, 10])

In [105]:
# Sum of X axis value
arrAxis.sum(axis=1)


array([ 6, 15,  8])

In [106]:
# ArgMax = Return Index of Max Elements by Axis Y
arrAxis.argmax(axis=0)


array([2, 1, 1], dtype=int64)

In [107]:
# ArgMin = Return Index of Min Elements by Axis Y
arrAxis.argmin(axis=0)


array([0, 2, 2], dtype=int64)

In [108]:
# ArgMax = Return Index of Max Elements by Axis X
arrAxis.argmax(axis=1)


array([2, 2, 0], dtype=int64)

In [109]:
# ArgMin = Return Index of Min Elements by Axis X
arrAxis.argmin(axis=1)


array([0, 0, 1], dtype=int64)

In [110]:
# Array ArgSort = Return the index of Sorted Order by value on Y axis
arrAxis.argsort(axis=0)


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [111]:
# Array ArgSort = Return the index of Sorted Order by value on X axis
arrAxis.argsort(axis=1)


array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [112]:
# Array Min = Return Minimum Value by axis Y
arrAxis.min(axis=0)


array([1, 0, 1])

In [113]:
# Array Min = Return Minimum Value by axis X
arrAxis.min(axis=1)


array([1, 4, 0])

In [114]:
# Array Max = Return Maximum Value by axis Y
arrAxis.max(axis=0)


array([7, 5, 6])

In [115]:
# Array Max = Return Maximum Value by axis X
arrAxis.max(axis=1)


array([3, 6, 7])

In [116]:
# Array Sort = Return Value by Sorted Order on axis Y
arrAxis.sort(axis=0)
print(arrAxis)


[[1 0 1]
 [4 2 3]
 [7 5 6]]


In [117]:
# Array Sort = Return Value by Sorted Order on axis X
arrAxis.sort(axis=1)
print(arrAxis)


[[0 1 1]
 [2 3 4]
 [5 6 7]]


# Numpy Transpose


In [118]:
# Transpose Matrix
arrAxis.T


array([[0, 2, 5],
       [1, 3, 6],
       [1, 4, 7]])

# Numpy NBytes


In [119]:
# Return array storage capacity in form of bytes
arrAxis.nbytes


36

# Numpy Array Operations


In [120]:
# M1 Array
M1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# M2 Array
M2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [121]:
# Addition
M1+M2


array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [122]:
# Subtraction
M2-M1


array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [123]:
# Multiplication
M1*M2


array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [124]:
# Division
M2/M1


array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [125]:
# Floor Division
M2//M1


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [126]:
# Modulus
M1 % M2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
# Power
M1**M2


array([[          1,     1048576, -1010140999],
       [          0,  1296002393,           0],
       [ 1187094929,           0,  -949019631]])

In [128]:
# Power
M2**M1


array([[        10,        400,      27000],
       [   2560000,  312500000, -588640256],
       [1977693568,          0, -779249152]])

In [129]:
# Left Shift
M2 << M1


array([[   20,    80,   240],
       [  640,  1600,  3840],
       [ 8960, 20480, 46080]])

In [130]:
# Right Shift
M2 >> M1


array([[5, 5, 3],
       [2, 1, 0],
       [0, 0, 0]])

In [204]:
# Dot Product
M1.dot(M2)


array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

# Numpy Square Root


In [131]:
arrSq = np.array([
    [5, 4, 9],
    [1, 2, 3],
    [6, 7, 8],
    [12, 15, 16],
])
arrSq


array([[ 5,  4,  9],
       [ 1,  2,  3],
       [ 6,  7,  8],
       [12, 15, 16]])

In [132]:
# Square Root all the values
np.sqrt(arrSq)


array([[2.23606798, 2.        , 3.        ],
       [1.        , 1.41421356, 1.73205081],
       [2.44948974, 2.64575131, 2.82842712],
       [3.46410162, 3.87298335, 4.        ]])

# Numpy Array Iteration


In [133]:
oneDArray = np.arange(10)
print(oneDArray)
for i in oneDArray:
    print(i)


[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [134]:
twoDArray = np.arange(10).reshape(2, 5)
print(twoDArray)
for i in twoDArray:
    for j in i:
        print(j)


[[0 1 2 3 4]
 [5 6 7 8 9]]
0
1
2
3
4
5
6
7
8
9


In [135]:
threeDArray = np.arange(20).reshape(2, 2, 5)
print(threeDArray)
for i in threeDArray:
    for j in i:
        for k in j:
            print(k)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [136]:
# Using Nditor
for i in np.nditer(threeDArray):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [137]:
# Using Nditor with Different Data Types
for i in np.nditer(oneDArray, flags=['buffered'], op_dtypes=['S']):
    print(i)


b'0'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [138]:
# Using Nditor with Different Step Size
for i in np.nditer(oneDArray[::2]):
    print(i)


0
2
4
6
8


In [139]:
# Using Ndenumerate 1-D Array
for idx, x in np.ndenumerate(oneDArray):
    print(idx, x)


(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9


In [140]:
# Using Ndenumerate 2-D Array
for idx, x in np.ndenumerate(twoDArray):
    print(idx, x)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [141]:
# Using Ndenumerate 3-D Array
for idx, x in np.ndenumerate(threeDArray):
    print(idx, x)


(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 0, 3) 3
(0, 0, 4) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 1, 4) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 0, 3) 13
(1, 0, 4) 14
(1, 1, 0) 15
(1, 1, 1) 16
(1, 1, 2) 17
(1, 1, 3) 18
(1, 1, 4) 19


# Numpy Array Join


In [142]:
# Using Concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mergeArr = np.concatenate((arr1, arr2))
mergeArr


array([1, 2, 3, 4, 5, 6])

In [143]:
# Using Concatenate
arr1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2 = np.array([[4, 5, 6], [10, 11, 12]])

mergeArr = np.concatenate((arr1, arr2))
mergeArr


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [144]:
# Using Stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mergeArr = np.stack((arr1, arr2))
mergeArr


array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
# Using Stack
arr1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2 = np.array([[4, 5, 6], [10, 11, 12]])

mergeArr = np.stack((arr1, arr2))
mergeArr


array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [146]:
# Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mergeArr = np.hstack((arr1, arr2))
mergeArr


array([1, 2, 3, 4, 5, 6])

In [147]:
# Stacking Along Rows
arr1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2 = np.array([[4, 5, 6], [10, 11, 12]])

mergeArr = np.hstack((arr1, arr2))
mergeArr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [148]:
# Stacking Along Columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mergeArr = np.vstack((arr1, arr2))
mergeArr


array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
# Stacking Along Columns
arr1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2 = np.array([[4, 5, 6], [10, 11, 12]])

mergeArr = np.vstack((arr1, arr2))
mergeArr


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [150]:
# Stacking Along Depth
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

mergeArr = np.dstack((arr1, arr2))
mergeArr


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [151]:
# Stacking Along Depth
arr1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2 = np.array([[4, 5, 6], [10, 11, 12]])

mergeArr = np.dstack((arr1, arr2))
mergeArr


array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

# Numpy Array Splitting


In [153]:
# Splitting 1-D Array
arrSp = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arrSp, 3)


[array([1, 2]), array([3, 4]), array([5, 6])]

In [157]:
# Splitting 1-D Array
arrSp = np.array([1, 2, 3, 4, 5, 6])
newArrSp = np.array_split(arrSp, 3)
print(newArrSp)
print(newArrSp[0])
print(newArrSp[1])
print(newArrSp[2])


[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [158]:
# Splitting 2-D Array
arrSp = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arrSp, 3)


[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [160]:
# Splitting 2-D Array
arrSp = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arrSp, 5)


[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [161]:
# Splitting 2-D Array
arrSp = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arrSp, 3, axis=1)


[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]

In [163]:
# Splitting 2-D Array
arrSp = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.split(arrSp, 3)


[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# Numpy Array Sorting


In [166]:
ak = np.array([78, -98, 42, -63, -98, 100, 254, 1, 3, 7, 6])
ak = np.sort(ak)
print(ak)


[-98 -98 -63   1   3   6   7  42  78 100 254]


In [167]:
ak = np.array(["kiwi", "orange", "pear", "grape", "watermelon",
              "pineapple", "strawberry", "banana", "apple", "mango"])
ak = np.sort(ak)
print(ak)


['apple' 'banana' 'grape' 'kiwi' 'mango' 'orange' 'pear' 'pineapple'
 'strawberry' 'watermelon']


In [168]:
ak = np.array([True, False, True, False, False,
              False, True, True, True, False])
ak = np.sort(ak)
print(ak)


[False False False False False  True  True  True  True  True]


In [169]:
ak = np.array([2 + 3j, -1 + 5j, 0 + 1j, 4 - 2j, -2 - 2j,
              3 + 7j, -4 + 6j, 1 - 8j, 5 + 4j, -6 - 3j])
ak = np.sort(ak)
print(ak)


[-6.-3.j -4.+6.j -2.-2.j -1.+5.j  0.+1.j  1.-8.j  2.+3.j  3.+7.j  4.-2.j
  5.+4.j]


# Numpy Array Searching


In [173]:
arrSe = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Return the searched element index in form of tuple
print(np.where(arrSe == 6))
print(np.where(arrSe > 7))


(array([5], dtype=int64),)
(array([7, 8, 9], dtype=int64),)


In [174]:
# Find the Even Value Index
np.where(arrSe % 2 == 0)


(array([1, 3, 5, 7, 9], dtype=int64),)

In [175]:
# Find the Odd Value Index
np.where(arrSe % 2 != 0)


(array([0, 2, 4, 6, 8], dtype=int64),)

In [177]:
arrSe = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(5, 2)
print(arrSe)
# Return the searched element index in form of tuple
print(np.where(arrSe == 4))
print(np.where(arrSe > 4))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(array([1], dtype=int64), array([1], dtype=int64))
(array([2, 2, 3, 3, 4, 4], dtype=int64), array([0, 1, 0, 1, 0, 1], dtype=int64))


# Numpy Array Search Sorted(Binary Search Process)


In [180]:
arrB = np.array([6, 7, 8, 9])
# Return the searched element index in form of tuple
np.searchsorted(arrB, 7)


1

In [181]:
arrB = np.array([6, 7, 8, 9])
# Return the searched element index from right side in form of tuple
np.searchsorted(arrB, 7, side='right')


2

In [183]:
arrB = np.array([6, 8, 10, 12])
# The return value is an array: [1 2 3] containing the three indexes where 7, 9, 11 would be inserted in the original array to maintain the order.
np.searchsorted(arrB, [7, 9, 11])


array([1, 2, 3], dtype=int64)

# Numpy Nonzeros


In [188]:
adf = np.array([0, 1, 5, 7, 0, 6, 8, 0, 1, 0, 9, 4])
# Return Total no of non zero elements
np.count_nonzero(adf)


8

In [189]:
# Return non zero elements index
np.nonzero(adf)


(array([ 1,  2,  3,  5,  6,  8, 10, 11], dtype=int64),)

In [193]:
adf = adf.reshape(3, 4)
adf


array([[0, 1, 5, 7],
       [0, 6, 8, 0],
       [1, 0, 9, 4]])

In [194]:
# Return non zero elements index
np.nonzero(adf)


(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 1, 2, 0, 2, 3], dtype=int64))

# Numpy Array Ones


In [203]:
# Create a 4 X 5 Array where each elements contains 1
arrOnes = np.ones((4, 5))
arrOnes


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#   Numpy Mean & Median

In [3]:
am=[0,1,23,4,5,6,7,89,10,1,2,1,5,1,52,1,44,5,1,5]
# Mean
np.mean(am)

13.15

In [4]:
# Median
np.median(am)

5.0

# Memory Size of Python List VS Numpy Array


In [195]:
# Import sys module
import sys


In [196]:
# Python List
py_list = [4, 55, 2, 68]
py_list


[4, 55, 2, 68]

In [197]:
# Numpy Array
np_arr = np.array(py_list)
np_arr


array([ 4, 55,  2, 68])

In [202]:
# Compare Memory Size
# 1.Python List Memory Size
print("Python List Memory Size is ", sys.getsizeof(1)*len(py_list))
# 1.Numpy Array Memory Size
print("Numpy Array Memory Size is ", np_arr.itemsize*np_arr.size)


Python List Memory Size is  112
Numpy Array Memory Size is  16
