#   Generate Random Number

In [1]:
# Import Random from Numpy
from numpy import random

In [2]:
# Generate a Random number from 0 to 100
random.randint(100)

96

In [3]:
# Generate a Float Random number from 0 to 1
random.rand()

0.6710146385678585

#   Generate Random Array

In [4]:
# Generate 1-D array containing 5 integers from 0 to 100
random.randint(100,size=(5))

array([58, 91, 28, 87, 50])

In [5]:
# Generate 2-D array containing 3-rows and each row containing 5 integers from 0 to 100
random.randint(100,size=(3,5))

array([[81, 38, 30, 41, 48],
       [37, 76, 45, 79,  5],
       [40, 99, 62, 16, 48]])

In [6]:
# Generate 1-D array containing 5 floats from 0 to 1
random.rand(5)

array([0.19352035, 0.20381131, 0.51807626, 0.38122311, 0.88985289])

In [7]:
# Generate 2-D array containing 3-rows and each row containing 5 floats from 0 to 1
random.rand(3,5)

array([[0.78248171, 0.89574874, 0.44560675, 0.81395234, 0.19937306],
       [0.72704231, 0.78489315, 0.73139636, 0.62354852, 0.52891555],
       [0.3230443 , 0.70026092, 0.33163712, 0.4990297 , 0.05562121]])

#   Generate Random Number From Array

In [8]:
# Return one of the values in an array
random.choice([3,5,7,9])

7

In [9]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)
random.choice([3,5,7,9],size=(3,5))

array([[3, 5, 7, 3, 7],
       [5, 9, 9, 5, 7],
       [5, 3, 3, 7, 3]])